# Generated by Django 5.1.7 on 2025-04-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='experience',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='fields',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='interests',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='job_preferences',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
