# Generated by Django 5.1.7 on 2025-04-29 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_joblisting_admin_feedback_joblisting_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cv_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cv_visible_to',
            field=models.ManyToManyField(blank=True, related_name='visible_candidate_cvs', to='core.employerprofile'),
        ),
    ]
