# Generated by Django 5.1.7 on 2025-04-29 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_cv_userprofile_cv_consent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cv_share_with_employers',
            field=models.BooleanField(default=False),
        ),
    ]
