# Generated by Django 5.1.7 on 2025-05-03 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_applicationtracking_rejectionemailtemplate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rejectionemail',
            name='application',
        ),
        migrations.RemoveField(
            model_name='rejectionemail',
            name='template',
        ),
        migrations.RemoveField(
            model_name='rejectionemailtemplate',
            name='employer',
        ),
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ApplicationTracking',
        ),
        migrations.DeleteModel(
            name='RejectionEmail',
        ),
        migrations.DeleteModel(
            name='RejectionEmailTemplate',
        ),
    ]
