# Generated by Django 5.1.7 on 2025-05-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_rejectionemail_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='guest_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
