# Generated by Django 5.1.7 on 2025-05-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_database_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='premium_level',
            field=models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('premium_plus', 'Premium +')], db_index=True, default='standard', max_length=20),
        ),
    ]
