# Generated by Django 5.1.7 on 2025-05-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_premium_levels_to_existing_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='considers_students',
            field=models.BooleanField(choices=[(True, 'კი'), (False, 'არა')], default=False),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='category',
            field=models.CharField(choices=[('მენეჯმენტი/ადმინისტრირება', 'მენეჯმენტი/ ადმინისტრირება'), ('მარკეტინგი', 'მარკეტინგი'), ('ფინანსები', 'ფინანსები'), ('გაყიდვები/მომხმარებელთან ურთიერთობა', 'გაყიდვები/მომხმარებელთან ურთიერთობა'), ('IT/პროგრამირება', 'IT/პროგრამირება'), ('დიზაინი', 'დიზაინი'), ('ჰორეკა/კვება', 'ჰორეკა/კვება'), ('დაცვა', 'დაცვა'), ('სილამაზე/მოდა', 'სილამაზე/მოდა'), ('მშენებლობა', 'მშენებლობა'), ('მედიცინა', 'მედიცინა'), ('განათლება', 'განათლება'), ('სამართალი', 'სამართალი'), ('ტურიზმი', 'ტურიზმი'), ('ლოჯისტიკა/დისტრიბუცია', 'ლოჯისტიკა/დისტრიბუცია'), ('საბანკო საქმე', 'საბანკო საქმე'), ('აზარტული', 'აზარტული')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='experience',
            field=models.CharField(choices=[('გამოცდილების გარეშე', 'გამოცდილების გარეშე'), ('დამწყები', 'დამწყები'), ('საშუალო დონე', 'საშუალო დონე'), ('პროფესიონალი', 'პროფესიონალი')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='job_preferences',
            field=models.CharField(choices=[('სრული განაკვეთი', 'სრული განაკვეთი'), ('ნახევარი განაკვეთი', 'ნახევარი განაკვეთი'), ('ცვლები', 'ცვლები')], max_length=255),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='location',
            field=models.CharField(choices=[('დისტანციური', 'დისტანციური'), ('თბილისი', 'თბილისი'), ('აჭარის ა/რ', 'აჭარის ა/რ'), ('აფხაზეთის ა/რ', 'აფხაზეთის ა/რ'), ('სვანეთი', 'სვანეთი'), ('სამეგრელო', 'სამეგრელო'), ('კახეთი', 'კახეთი'), ('ლეჩხუმი', 'ლეჩხუმი'), ('რაჭა', 'რაჭა'), ('გურია', 'გურია'), ('ქვემო ქართლი', 'ქვემო ქართლი'), ('სამცხე-ჯავახეთი', 'სამცხე-ჯავახეთი'), ('შიდა ქართლი', 'შიდა ქართლი'), ('მცხეთა-მთიანეთი', 'მცხეთა-მთიანეთი'), ('იმერეთი', 'იმერეთი')], db_index=True, max_length=100),
        ),
    ]
