# Generated by Django 5.1.7 on 2025-05-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_joblisting_considers_students_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='salary_type',
            field=models.CharField(choices=[('თვეში', 'თვეში'), ('კვირაში', 'კვირაში'), ('დღეში', 'დღეში'), ('საათში', 'საათში')], default='თვეში', max_length=50),
        ),
    ]
