# Generated by Django 5.1.7 on 2025-05-15 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_joblisting_salary_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employerprofile',
            options={'verbose_name': 'დამსაქმებლის პროფილი', 'verbose_name_plural': 'დამსაქმებლების პროფილები'},
        ),
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ['-applied_at'], 'verbose_name': 'აპლიკაცია', 'verbose_name_plural': 'აპლიკაციები'},
        ),
        migrations.AlterModelOptions(
            name='joblisting',
            options={'ordering': ['-posted_at'], 'verbose_name': 'ვაკანსია', 'verbose_name_plural': 'ვაკანსიები'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'მომხმარებლის პროფილი', 'verbose_name_plural': 'მომხმარებლების პროფილები'},
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='company_description',
            field=models.TextField(blank=True, verbose_name='კომპანიის აღწერა'),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='კომპანიის ლოგო'),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='company_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='კომპანიის დასახელება'),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='company_size',
            field=models.CharField(blank=True, choices=[('1-10', '1-10 employees'), ('11-50', '11-50 employees'), ('51-200', '51-200 employees'), ('201-500', '201-500 employees'), ('501-1000', '501-1000 employees'), ('1001+', '1001+ employees')], max_length=50, verbose_name='კომპანიის ზომა'),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='company_website',
            field=models.URLField(blank=True, verbose_name='კომპანიის ვებსაიტი'),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='შექმნის თარიღი'),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='industry',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='ინდუსტრია'),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='location',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='მდებარეობა'),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='განახლების თარიღი'),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_profile', to='core.userprofile', verbose_name='მომხმარებლის პროფილი'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='applied_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='აპლიკაციის თარიღი'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='cover_letter',
            field=models.TextField(verbose_name='მოტივაციის წერილი'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='სტუმრის ელ-ფოსტა'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='guest_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='სტუმრის სახელი'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.joblisting', verbose_name='ვაკანსია'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(upload_to='resumes/', verbose_name='რეზიუმე'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('განხილვის_პროცესში', 'განხილვის პროცესში'), ('გასაუბრება', 'გასაუბრება'), ('რეზერვი', 'რეზერვი'), ('pending', 'Pending'), ('reviewed', 'Reviewed'), ('interviewed', 'Interviewed'), ('offered', 'Offer Extended'), ('accepted', 'Offer Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], db_index=True, default='განხილვის_პროცესში', max_length=30, verbose_name='სტატუსი'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='განახლების თარიღი'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='მომხმარებელი'),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='admin_feedback',
            field=models.TextField(blank=True, verbose_name='ადმინის უკუკავშირი'),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='category',
            field=models.CharField(choices=[('მენეჯმენტი/ადმინისტრირება', 'მენეჯმენტი/ ადმინისტრირება'), ('მარკეტინგი', 'მარკეტინგი'), ('ფინანსები', 'ფინანსები'), ('გაყიდვები/მომხმარებელთან ურთიერთობა', 'გაყიდვები/მომხმარებელთან ურთიერთობა'), ('IT/პროგრამირება', 'IT/პროგრამირება'), ('დიზაინი', 'დიზაინი'), ('ჰორეკა/კვება', 'ჰორეკა/კვება'), ('დაცვა', 'დაცვა'), ('სილამაზე/მოდა', 'სილამაზე/მოდა'), ('მშენებლობა', 'მშენებლობა'), ('მედიცინა', 'მედიცინა'), ('განათლება', 'განათლება'), ('სამართალი', 'სამართალი'), ('ტურიზმი', 'ტურიზმი'), ('ლოჯისტიკა/დისტრიბუცია', 'ლოჯისტიკა/დისტრიბუცია'), ('საბანკო საქმე', 'საბანკო საქმე'), ('აზარტული', 'აზარტული')], db_index=True, max_length=100, verbose_name='კატეგორია'),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='company',
            field=models.CharField(db_index=True, max_length=100, verbose_name='კომპანია'),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='considers_students',
            field=models.BooleanField(choices=[(True, 'კი'), (False, 'არა')], default=False, verbose_name='განიხილავს სტუდენტებს'),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='description',
            field=models.TextField(verbose_name='ვაკანსიის აღწერა'),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_listings', to='core.employerprofile', verbose_name='დამსაქმებელი'),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='experience',
            field=models.CharField(choices=[('გამოცდილების გარეშე', 'გამოცდილების გარეშე'), ('დამწყები', 'დამწყები'), ('საშუალო დონე', 'საშუალო დონე'), ('პროფესიონალი', 'პროფესიონალი')], db_index=True, max_length=100, verbose_name='გამოცდილება'),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='fields',
            field=models.CharField(blank=True, max_length=255, verbose_name='სფეროები'),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='interests',
            field=models.CharField(blank=True, max_length=255, verbose_name='ინტერესები'),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='job_preferences',
            field=models.CharField(choices=[('სრული განაკვეთი', 'სრული განაკვეთი'), ('ნახევარი განაკვეთი', 'ნახევარი განაკვეთი'), ('ცვლები', 'ცვლები')], max_length=255, verbose_name='სამუშაო გრაფიკი'),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='location',
            field=models.CharField(choices=[('დისტანციური', 'დისტანციური'), ('თბილისი', 'თბილისი'), ('აჭარა', 'აჭარა'), ('აფხაზეთი', 'აფხაზეთი'), ('სვანეთი', 'სვანეთი'), ('სამეგრელო', 'სამეგრელო'), ('კახეთი', 'კახეთი'), ('ლეჩხუმი', 'ლეჩხუმი'), ('რაჭა', 'რაჭა'), ('გურია', 'გურია'), ('ქვემო ქართლი', 'ქვემო ქართლი'), ('სამცხე-ჯავახეთი', 'სამცხე-ჯავახეთი'), ('შიდა ქართლი', 'შიდა ქართლი'), ('მცხეთა-მთიანეთი', 'მცხეთა-მთიანეთი'), ('იმერეთი', 'იმერეთი')], db_index=True, max_length=100, verbose_name='ლოკაცია'),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='posted_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='გამოქვეყნების თარიღი'),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='premium_level',
            field=models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('premium_plus', 'Premium +')], db_index=True, default='standard', max_length=20, verbose_name='პრემიუმ დონე'),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='salary_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='მაქსიმალური ხელფასი'),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='salary_min',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=10, null=True, verbose_name='მინიმალური ხელფასი'),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='salary_type',
            field=models.CharField(choices=[('თვეში', 'თვეში'), ('კვირაში', 'კვირაში'), ('დღეში', 'დღეში'), ('საათში', 'საათში')], default='თვეში', max_length=50, verbose_name='ხელფასის ტიპი'),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='status',
            field=models.CharField(choices=[('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending_review', max_length=20, verbose_name='სტატუსი'),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='title',
            field=models.CharField(db_index=True, max_length=100, verbose_name='ვაკანსიის დასახელება'),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='განახლების თარიღი'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='შექმნის თარიღი'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/', verbose_name='CV'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cv_consent',
            field=models.BooleanField(default=False, verbose_name='CV-ის გაზიარების თანხმობა'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cv_share_with_employers',
            field=models.BooleanField(default=False, verbose_name='CV-ის გაზიარება დამსაქმებლებთან'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cv_visible_to',
            field=models.ManyToManyField(blank=True, related_name='visible_candidate_cvs', to='core.employerprofile', verbose_name='CV-ის ხილვადობა'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='პროფილის სურათი'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('candidate', 'Candidate'), ('employer', 'Employer'), ('admin', 'Admin')], db_index=True, default='candidate', max_length=20, verbose_name='როლი'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='მომხმარებელი'),
        ),
    ]
