# Generated by Django 5.1.7 on 2025-05-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_savedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='company_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='საიდენტიფიკაციო კოდი'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='მობილურის ნომერი'),
        ),
    ]
