# Generated by Django 5.1.7 on 2025-05-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_employerprofile_company_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='წაშლის თარიღი'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='წაშლის თარიღი'),
        ),
    ]
