# Generated by Django 5.1.7 on 2025-05-17 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_employerprofile_deleted_at_joblisting_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='job_company',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='კომპანია'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ვაკანსიის სათაური'),
        ),
        migrations.AddField(
            model_name='savedjob',
            name='job_company',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='კომპანია'),
        ),
        migrations.AddField(
            model_name='savedjob',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ვაკანსიის სათაური'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='core.joblisting', verbose_name='ვაკანსია'),
        ),
        migrations.AlterField(
            model_name='savedjob',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_by', to='core.joblisting', verbose_name='ვაკანსია'),
        ),
    ]
