# Generated by Django 5.1.7 on 2025-05-17 10:57

from django.db import migrations

def populate_job_fields(apps, schema_editor):
    """
    Populate job_title and job_company fields for all JobApplication and SavedJob records
    where job is not null.
    """
    JobApplication = apps.get_model('core', 'JobApplication')
    SavedJob = apps.get_model('core', 'SavedJob')
    
    # Update JobApplications
    for application in JobApplication.objects.filter(job__isnull=False):
        if not application.job_title or not application.job_company:
            application.job_title = application.job.title
            application.job_company = application.job.company
            application.save(update_fields=['job_title', 'job_company'])
    
    # Update SavedJobs
    for saved_job in SavedJob.objects.filter(job__isnull=False):
        if not saved_job.job_title or not saved_job.job_company:
            saved_job.job_title = saved_job.job.title
            saved_job.job_company = saved_job.job.company
            saved_job.save(update_fields=['job_title', 'job_company'])

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_jobapplication_job_company_jobapplication_job_title_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_job_fields, migrations.RunPython.noop),
    ]
