# Generated by Django 5.1.7 on 2025-05-19 15:33

import jobsy.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_populate_job_titles'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='georgian_language_only',
            field=models.BooleanField(choices=[(True, 'კი'), (False, 'არა')], default=False, verbose_name='პოზიციაზე მოთხოვნილია მხოლოდ ქართული ენის ცოდნა'),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, storage=jobsy.storage_backends.PublicMediaStorage(), upload_to='company_logos/', verbose_name='კომპანიის ლოგო'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume',
            field=models.FileField(storage=jobsy.storage_backends.PrivateMediaStorage(), upload_to='resumes/', verbose_name='რეზიუმე'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cv',
            field=models.FileField(blank=True, null=True, storage=jobsy.storage_backends.PrivateMediaStorage(), upload_to='cvs/', verbose_name='CV'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage=jobsy.storage_backends.PublicMediaStorage(), upload_to='profile_pictures/', verbose_name='პროფილის სურათი'),
        ),
    ]
