# Generated by Django 5.1.7 on 2025-05-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_add_georgian_language_only_field'),
    ]

    operations = [
        # First, modify the field to allow NULL temporarily
        migrations.AlterField(
            model_name='joblisting',
            name='georgian_language_only',
            field=models.BooleanField(choices=[(True, 'კი'), (False, 'არა')], default=False, null=True, verbose_name='პოზიციაზე მოთხოვნილია მხოლოდ ქართული ენის ცოდნა'),
        ),
        # Then, update any NULL values to False
        migrations.RunSQL(
            sql="UPDATE core_joblisting SET georgian_language_only = FALSE WHERE georgian_language_only IS NULL;",
            reverse_sql="",
        ),
        # Finally, restore the NOT NULL constraint
        migrations.AlterField(
            model_name='joblisting',
            name='georgian_language_only',
            field=models.BooleanField(choices=[(True, 'კი'), (False, 'არა')], default=False, verbose_name='პოზიციაზე მოთხოვნილია მხოლოდ ქართული ენის ცოდნა'),
        ),
    ]
