# Generated by Django 5.1.7 on 2025-05-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_fix_georgian_language_field_null_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='ვადის გასვლის თარიღი'),
        ),
        migrations.AddIndex(
            model_name='joblisting',
            index=models.Index(fields=['expires_at'], name='core_joblis_expires_ea202e_idx'),
        ),
    ]
