# Generated by Django 5.1.7 on 2025-05-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_joblisting_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False, verbose_name='წაკითხულია'),
        ),
    ]
