# Generated by Django 5.1.7 on 2025-05-20 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_jobapplication_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='cv_consent',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cv_share_with_employers',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cv_visible_to',
        ),
    ]
