# Generated by Django 5.1.7 on 2025-05-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_cv_consent_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectionReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='მიზეზი')),
            ],
            options={
                'verbose_name': 'უარის მიზეზი',
                'verbose_name_plural': 'უარის მიზეზები',
            },
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='feedback',
            field=models.TextField(blank=True, verbose_name='უკუკავშირი'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='rejection_reasons',
            field=models.ManyToManyField(blank=True, related_name='applications', to='core.rejectionreason', verbose_name='უარის მიზეზები'),
        ),
    ]
