# Generated by Django 5.1.7 on 2025-05-24 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_jobapplication_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_type', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('premium_plus', 'Premium Plus')], max_length=20, unique=True, verbose_name='Package Type')),
                ('name', models.CharField(max_length=100, verbose_name='Package Name')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Original Price')),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Current Price')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Is Popular')),
                ('is_free', models.BooleanField(default=False, verbose_name='Is Free')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Pricing Package',
                'verbose_name_plural': 'Pricing Packages',
                'ordering': ['display_order', 'package_type'],
            },
        ),
        migrations.CreateModel(
            name='PricingFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Feature Text')),
                ('is_included', models.BooleanField(default=True, verbose_name='Is Included')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='Display Order')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='core.pricingpackage', verbose_name='Package')),
            ],
            options={
                'verbose_name': 'Pricing Feature',
                'verbose_name_plural': 'Pricing Features',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
